### ISSUE TITLE
Invoke-IcingaCheckCPU: Passing ThresholdInterval argument causes "No checks added to this package" error

### ISSUE THREAD

**Issue by atj** [Icinga/icinga-powershell-framework#605]
## Expected Behavior

Passing the `-ThresholdInterval` argument shouldn't cause the plugin to fail.

## Current Behavior

The "-Core" argument seems to be the cause of this, however even without it the `-ThresholdInterval` argument has no effect:

```powershell
#  with -Core argument
> Exit-IcingaExecutePlugin `
    -Command Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90 `
    -Core '_Total' `
    -ThresholdInterval 5m
[UNKNOWN] CPU Load: No checks added to this package

# without -Core argument
# check runs but the threshold is applied to the current load and not the interval
> Exit-IcingaExecutePlugin `
    -Command Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90 `
    -ThresholdInterval 5m
[OK] CPU Load
| 'total::ifw_cpu::load'=6.828915%;80;90;0;100 'load15m'=8.711755%;;;0;100 'load1m'=7.243660%;;;0;100 'load5m'=11.968226%;;;0;100 '0::ifw_cpu::load'=7.176533%;80;90;0;100 'load15m'=8.925831%;
;;0;100 'load1m'=7.549128%;;;0;100 'load5m'=12.214635%;;;0;100 '1::ifw_cpu::load'=6.481296%;80;90;0;100 'load15m'=8.568474%;;;0;100 'load1m'=6.938192%;;;0;100 'load5m'=11.949938%;;;0;100
```

Debug output from eventlog:

```
Object details:
Receiving client message

POST /v1/checker?command=Invoke-IcingaCheckCPU HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859
Content-Type: application/json
Host: localhost:5668
Content-Length: 66
Connection: Keep-Alive

Object details:
Body Content

Name                           Value                                                               
----                           -----                                                               
Method                         POST                                                                
RequestPath                    {FullPath, PathArray}                                               
Header                         {User-Agent, Host, Content-Type, Connection...}                     
RequestArguments               {command}                                                           
Body                           {"Critical":90,"Core":"_Total -ThresholdInterval 5m","Warning":80}  
FullRequest                    /v1/checker?command=Invoke-IcingaCheckCPU                           
ContentLength                  66                                                                  

Object details:
Check Executed. Result below
Invoke-IcingaCheckCPU
[UNKNOWN] CPU Load: No checks added to this package
3

Object details:
Sending message to client
HTTP/1.1 200 Ok
Server: xxx
Content-Type: application/json
Content-Length: 122

{"Invoke-IcingaCheckCPU":{"exitcode":3,"checkresult":"[UNKNOWN] CPU Load: No checks added to this package","perfdata":[]}}
```

```
Object details:
Receiving client message

POST /v1/checker?command=Invoke-IcingaCheckCPU HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.20348.859
Content-Type: application/json
Host: localhost:5668
Content-Length: 28

Object details:
Body Content

Name                           Value                                                               
----                           -----                                                               
Method                         POST                                                                
RequestPath                    {FullPath, PathArray}                                               
Header                         {User-Agent, Host, Content-Type, Content-Length}                    
RequestArguments               {command}                                                           
Body                           {"Critical":90,"Warning":80}                                        
FullRequest                    /v1/checker?command=Invoke-IcingaCheckCPU                           
ContentLength                  28      

Object details:
Check Executed. Result below

Invoke-IcingaCheckCPU
[OK] CPU Load
'total::ifw_cpu::load'=6.50981%;80;90;0;100 'load15m'=8.500680%;;;0;100 'load1m'=9.859584%;;;0;100 'load5m'=7.121220%;;;0;100
'0::ifw_cpu::load'=6.50981%;80;90;0;100 'load15m'=8.651429%;;;0;100 'load1m'=10.004470%;;;0;100 'load5m'=7.249404%;;;0;100
'1::ifw_cpu::load'=6.50981%;80;90;0;100 'load15m'=8.420661%;;;0;100 'load1m'=9.671310%;;;0;100 'load5m'=6.992846%;;;0;100
0

Object details:
Sending message to client
HTTP/1.1 200 Ok
Server: xxx
Content-Type: application/json
Content-Length: 580

{"Invoke-IcingaCheckCPU":{"exitcode":0,"checkresult":"[OK] CPU Load","perfdata":["\u0027total::ifw_cpu::load\u0027=6.50981%;80;90;0;100 \u0027load15m\u0027=8.500680%;;;0;100 \u0027load1m\u0027=9.859584%;;;0;100 \u0027load5m\u0027=7.121220%;;;0;100","\u00270::ifw_cpu::load\u0027=6.50981%;80;90;0;100 \u0027load15m\u0027=8.651429%;;;0;100 \u0027load1m\u0027=10.004470%;;;0;100 \u0027load5m\u0027=7.249404%;;;0;100","\u00271::ifw_cpu::load\u0027=6.50981%;80;90;0;100 \u0027load15m\u0027=8.420661%;;;0;100 \u0027load1m\u0027=9.671310%;;;0;100 \u0027load5m\u0027=6.992846%;;;0;100"]}}
```

Note that when the `-Core` argument is specified the API request body shows that the `-ThresholdInterval` argument is subsumed into the value:

```json
{"Critical":90,"Core":"_Total -ThresholdInterval 5m","Warning":80}
```

and without the `-Core` argument `-ThresholdInterval` is completely omitted:

```json
 {"Critical":90,"Warning":80}
```

So it looks like some sort of bug with the command line parsing. Not sure if it's related to the API check forwarder?

## Your Environment

```powershell
> Show-Icinga
Icinga for Windows environment:
-----------


Environment configuration:

PowerShell Root                 => C:\Program Files\WindowsPowerShell\Modules\
Icinga for Windows Service Path => C:\Program Files\icinga-framework-service\
Icinga for Windows Service User => NT AUTHORITY\NetworkService
Icinga for Windows Service Pid  => 5740
Icinga for Windows JEA Pid      => 
Icinga Agent Path               => C:\Program Files\ICINGA2\
Icinga Agent User               => NT AUTHORITY\NetworkService
Defined Default User            => NT AUTHORITY\NetworkService
Icinga Managed User             => False
PowerShell Version              => 5.1.20348.859
Operating System                => Microsoft Windows Server 2022 Standard
Operating System Version        => 10.0.20348
JEA Context                     => 
JEA Session File                => 
Api Check Forwarder             => True
Debug Mode                      => True

Icinga for Windows Certificate:

Not installed

List of configured background daemons on this system:

Start-IcingaServiceCheckDaemon
-----------
No arguments defined

Start-IcingaWindowsRESTApi
-----------
No arguments defined

List of configured background service checks on this system:
=> https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/06-Collect-Metrics-over-Time/

Invoke-IcingaCheckCPU
-----------
Arguments    => 
CheckCommand => Invoke-IcingaCheckCPU
Id           => 5275219864641021224811420224776891459631192206
Interval     => 30
TimeIndexes  => 60, 300, 900

List of configured repositories on this system. The list order matches the apply order:

Icinga Stable
-----------
CloneSource  => 
Enabled      => True
LocalPath    => 
Order        => 0
RemotePath   => https://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json
UseSCP       => False

Installed components on this system:

Component    Version   Available
---          ---       ---
agent        2.13.6    2.13.6
apichecks    1.2.0     1.2.0
framework    1.10.1    1.10.1
plugins      1.10.1    1.10.1
restapi      1.2.0     1.2.0
service      1.2.0     1.2.0
```

**Comment by LordHepipud** [comment]
This should be fixed by #618 - can you please verify this?

**Comment by atj** [comment]
How do I install the version of the framework from master?

In any case I can't get the plugin to return interval metrics at all:

```
PS C:\WINDOWS\system32> [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11';
$ProgressPreference                         = 'SilentlyContinue';
[string]$ScriptFile                         = 'C:\Users\Public\IcingaForWindows.ps1';

Invoke-WebRequest `
    -UseBasicParsing `
    -Uri 'https://packages.icinga.com/IcingaForWindows/IcingaForWindows.ps1' `
    -OutFile $ScriptFile;


& $ScriptFile -SkipWizard;
[Notice]: PowerShell Execution-Policies are configured to run Scripts and/or Modules.
The following directories are available for installing PowerShell modules into:
[0]: C:\Users\atj\Documents\WindowsPowerShell\Modules
[1]: C:\Program Files\WindowsPowerShell\Modules (Recommended)
[2]: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
Where do you want to install the Icinga PowerShell Framework into? ([0-2]) (Defaults: "1"): 
[Notice]: Downloading Icinga PowerShell Framework into "C:\Users\atj\AppData\Local\Temp\icinga-powershell-framework-zip"
[Notice]: Installing Icinga PowerShell Framework into "C:\Program Files\WindowsPowerShell\Modules"
[Notice]: Installing new Icinga PowerShell Framework version
[Notice]: Unblocking Icinga PowerShell Framework files
[Notice]: Applying pending migrations required for Icinga for Windows v1.8.0
[Notice]: Applying pending migrations required for Icinga for Windows v1.10.0
[Notice]: Applying pending migrations required for Icinga for Windows v1.10.1
[Notice]: Icinga PowerShell Framework seems to be successfully installed
[Notice]: To use the Icinga PowerShell Framework in the future, please initialize it by running the command "Use-Icinga" inside your PowerShell

PS C:\WINDOWS\system32> Use-Icinga;

PS C:\WINDOWS\system32> Add-IcingaRepository `
    -Name 'Icinga Stable' `
    -RemotePath 'https://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json';
[Notice]: Remote repository "Icinga Stable" was successfully added

PS C:\WINDOWS\system32> Install-IcingaComponent -Name service;
Do you want to install component "service" from source "Icinga Stable" (https://packages.icinga.com/IcingaForWindows/stable/service/icinga-service-v1.2.0.zip)? (Y/n): 
[Notice]: Downloading "service" from "https://packages.icinga.com/IcingaForWindows/stable/service/icinga-service-v1.2.0.zip"
[Notice]: Installing component "service" into "C:\Program Files\icinga-framework-service"
[Notice]: Updating Icinga PowerShell Service binary
[Notice]: Service User ".\LocalSystem" for service "icingapowershell" successfully updated
[Notice]: Stopping service "icingapowershell"
[Notice]: Restarting service "icingapowershell"
[Notice]: Stopping service "icingapowershell"
[Notice]: Service User "NT Authority\NetworkService" for service "icingapowershell" successfully updated
[Notice]: Installation of component "service" was successful

PS C:\WINDOWS\system32> Install-IcingaComponent -Name 'plugins';
Do you want to install component "plugins" from source "Icinga Stable" (https://packages.icinga.com/IcingaForWindows/stable/plugins/icinga-powershell-plugins-1.10.1.zip)?
 (Y/n): 
[Notice]: Downloading "plugins" from "https://packages.icinga.com/IcingaForWindows/stable/plugins/icinga-powershell-plugins-1.10.1.zip"
[Notice]: Installing version "1.10.1" of component "plugins"
[Notice]: Unblocking Icinga PowerShell Files
[Notice]: Installation of component "plugins" with version "1.10.1" was successful. Open a new PowerShell to apply the changes

PS C:\WINDOWS\system32> Register-IcingaServiceCheck `
    -CheckCommand 'Invoke-IcingaCheckCPU' `
    -Interval 30 `
    -TimeIndexes 1, 3, 5, 15;
[Notice]: Icinga background service check has been added

PS C:\WINDOWS\system32> Show-IcingaRegisteredServiceChecks;
List of configured background service checks on this system:
=> https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/06-Collect-Metrics-over-Time/

Invoke-IcingaCheckCPU
-----------
Arguments    => 
CheckCommand => Invoke-IcingaCheckCPU
Id           => 5275219864641021224811420224776891459631192206
Interval     => 30
TimeIndexes  => 1, 3, 5, 15

PS C:\WINDOWS\system32> Restart-IcingaWindowsService;
[Notice]: Stopping service "icingapowershell"
[Notice]: Restarting service "icingapowershell"

PS C:\WINDOWS\system32> Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90 `
    -Core '_Total' `
    -ThresholdInterval 5m
[OK] CPU Load
| 'total::ifw_cpu::load'=2.693268%;80;90;0;100
0

PS C:\WINDOWS\system32> Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90 `
    -ThresholdInterval 5m
[OK] CPU Load
| 'total::ifw_cpu::load'=0.928453%;80;90;0;100 '0::ifw_cpu::load'=0.541606%;80;90;0;100 '1::ifw_cpu::load'=1.3153%;80;90;0;100
0

PS C:\WINDOWS\system32> Show-Icinga;
Icinga for Windows environment:
-----------


Environment configuration:

PowerShell Root                 => C:\Program Files\WindowsPowerShell\Modules\
Icinga for Windows Service Path => C:\Program Files\icinga-framework-service\
Icinga for Windows Service User => NT Authority\NetworkService
Icinga for Windows Service Pid  => 6656
Icinga for Windows JEA Pid      => 
Icinga Agent Path               => 
Icinga Agent User               => NT AUTHORITY\NetworkService
Defined Default User            => NT Authority\NetworkService
Icinga Managed User             => False
PowerShell Version              => 5.1.19041.2673
Operating System                => Microsoft Windows 10 Pro
Operating System Version        => 10.0.19044
JEA Context                     => 
JEA Session File                => 
Api Check Forwarder             => False
Debug Mode                      => False

Icinga for Windows Certificate:

Not installed

List of configured background daemons on this system:

Start-IcingaServiceCheckDaemon
-----------
No arguments defined

List of configured background service checks on this system:
=> https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/06-Collect-Metrics-over-Time/

Invoke-IcingaCheckCPU
-----------
Arguments    => 
CheckCommand => Invoke-IcingaCheckCPU
Id           => 5275219864641021224811420224776891459631192206
Interval     => 30
TimeIndexes  => 1, 3, 5, 15

List of configured repositories on this system. The list order matches the apply order:

Icinga Stable
-----------
CloneSource  => 
Enabled      => True
LocalPath    => 
Order        => 0
RemotePath   => https://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json
UseSCP       => False

Installed components on this system:

Component    Version   Available
---          ---       ---
framework    1.10.1    1.10.1
plugins      1.10.1    1.10.1
service      1.2.0     1.2.0

Available versions flagged with "*" mean that this component is locked to this version
```

**Comment by LordHepipud** [comment]
#622

**Comment by atj** [comment]
Thanks for updating the docs.

It's still not working for me unfortunately. Is the use of the API check forwarder a requirement now? I'm trying to test locally without a configured Icinga Agent instance.

```
PS C:\WINDOWS\system32> Register-IcingaServiceCheck `
    -CheckCommand 'Invoke-IcingaCheckCPU' `
    -Interval 30 `
    -TimeIndexes 1m, 3m, 5m, 15m;
[Notice]: Icinga background service check has been added

PS C:\WINDOWS\system32> Show-IcingaRegisteredServiceChecks;
List of configured background service checks on this system:
=> https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/06-Collect-Metrics-over-Time/

Invoke-IcingaCheckCPU
-----------
Arguments    => 
CheckCommand => Invoke-IcingaCheckCPU
Id           => 5275219864641021224811420224776891459631192206
Interval     => 30
TimeIndexes  => 1m, 3m, 5m, 15m

PS C:\WINDOWS\system32> Restart-IcingaWindowsService;
[Notice]: Stopping service "icingapowershell"
[Notice]: Restarting service "icingapowershell"

PS C:\WINDOWS\system32> Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90 `
    -ThresholdInterval 1m
[OK] CPU Load
| 'total::ifw_cpu::load'=6.70647%;80;90;0;100 '0::ifw_cpu::load'=7.142874%;80;90;0;100 '1::ifw_cpu::load'=6.547636%;80;90;0;100
0

PS C:\WINDOWS\system32> Invoke-IcingaCheckCPU `
    -Warning 80 `
    -Critical 90
[OK] CPU Load
| 'total::ifw_cpu::load'=7.889177%;80;90;0;100 '0::ifw_cpu::load'=8.955278%;80;90;0;100 '1::ifw_cpu::load'=6.823084%;80;90;0;100
0
```

**Comment by atj** [comment]
Finally got around to testing this with a properly registered agent and it appears to be fixed. Thanks!
